# --------------------------------------------------------
# Octree-based Sparse Convolutional Neural Networks
# Copyright (c) 2022 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: train
  logdir: logs/scannet/D9_2cm
  max_epoch: 600
  test_every_epoch: 10
  log_per_iter: 20
  weight_decay: 0.0001

  # learning rate
  lr: 0.05
  lr_type: poly
  step_size: (200,300)  # has no effect for `poly`

DATA:
  train:
    name: scannet

    # octree building
    depth: 9
    full_depth: 2

    # data augmentations
    distort: True
    angle: (0, 0, 180)
    scale: 0.1
    jitter: 0.1
    uniform: True

    # data loading
    location: data/scannet/train
    filelist: data/scannet/scannetv2_train_new.txt
    batch_size: 4
    shuffle: True
    # num_workers: 0

  test:
    name: scannet

    # octree building
    depth: 9
    full_depth: 2

    # data augmentations
    distort: False  # no data augmentation
    angle: (0, 0, 180)
    scale: 0.1
    jitter: 0.1
    uniform: True

    # data loading
    location: data/scannet/train
    filelist: data/scannet/scannetv2_val_new.txt
    batch_size: 1
    shuffle: False
    # num_workers: 0

MODEL:
  name: unet
  feature: NDF # N -> Normal (3 channels);
               # D -> Displacement (1 channel);
               # F -> Color (3 channels)
  channel: 7
  nout: 21
  nempty: True
  interp: nearest
  sync_bn: False

LOSS:
  mask: 0
  num_class: 21
